version: '3.8'

services:
  backend:
    build:
      context: ./movie-app-backend-master
      dockerfile: Dockerfile
    image: abhishekjadhav1996/movie-backend:latest
    container_name: movie-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT}
    restart: unless-stopped

  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: abhishekjadhav1996/movie-gateway:latest
    container_name: movie-gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - .env
    environment:
      - PORT=${GATEWAY_PORT}
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./movie-app-frontend-master
      dockerfile: Dockerfile
    image: abhishekjadhav1996/movie-frontend:latest
    container_name: movie-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    depends_on:
      gateway:
        condition: service_started
    restart: unless-stopped




# version: "3.9"

# services:
#   backend:
#     build:
#       context: ./movie-app-backend-master
#       dockerfile: Dockerfile
#     image: abhishekjadhav1996/movie-backend:latest
#     container_name: movie-backend
#     ports:
#       - "${BACKEND_PORT}:${BACKEND_PORT}"
#     environment:
#       - PORT=${BACKEND_PORT}
#       - MONGO_URI=${MONGO_URI}   # use the full URI from Jenkins credentials
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 15s

#   gateway:
#     build:
#       context: ./api-gateway
#       dockerfile: Dockerfile
#     image: abhishekjadhav1996/movie-gateway:latest
#     container_name: movie-gateway
#     ports:
#       - "${GATEWAY_PORT}:${GATEWAY_PORT}"
#     environment:
#       - PORT=${GATEWAY_PORT}
#       - BACKEND_URL=http://backend:${BACKEND_PORT}
#     depends_on:
#       - backend
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:${GATEWAY_PORT}/health"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 15s

#   frontend:
#     build:
#       context: ./movie-app-frontend-master
#       dockerfile: Dockerfile
#     image: abhishekjadhav1996/movie-frontend:latest
#     container_name: movie-frontend
#     ports:
#       - "${FRONTEND_PORT}:3000"
#     environment:
#       - REACT_APP_API_URL=http://gateway:${GATEWAY_PORT}
#     depends_on:
#       - gateway
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:3000"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 20s

# version: "3.9"

# services:
#   backend:
#     build: ./movie-app-backend-master
#     container_name: movie-backend
#     ports:
#       - "5000:5000"
#     environment:
#       DB_HOST: "${DB_HOST}"
#       DB_USER: "${DB_USER}"
#       DB_PASSWORD: "${DB_PASSWORD}"

#   gateway:
#     build: ./api-gateway
#     container_name: movie-gateway
#     ports:
#       - "8000:8000"
#     depends_on:
#       - backend
#     environment:
#       BACKEND_URL: "http://backend:5000"

#   frontend:
#     build: ./movie-app-frontend-master
#     container_name: movie-frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - gateway
#     environment:
#       API_GATEWAY_URL: "http://gateway:8000"
